apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replicaset
  labels:
    app: online-inference
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference-replicaset
      labels:
        app: online-inference
    spec:
      containers:
        - name: online-inference
          image: ivantrenev/online_inference:v_test
          ports:
            - containerPort: 9000